services:
  # 1. ฐานข้อมูล PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bma_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bma_db
    ports:
      - "5432:5432"
    volumes:
      - bma_pg_data:/var/lib/postgresql/data

volumes:
  bma_pg_data: