-- Ensure every attachment category used by the workspace has a lookup row.
-- The lookup ID is intentionally generated by PostgreSQL; the frontend resolves
-- IDs by doc_type_name and never relies on a numeric constant.
SELECT setval(
  pg_get_serial_sequence('project_attachment_types', 'doc_type_id'),
  GREATEST((SELECT COALESCE(MAX("doc_type_id"), 1) FROM "project_attachment_types"), 1),
  true
);
--> statement-breakpoint
INSERT INTO "project_attachment_types" ("doc_type_name")
SELECT 'system_diagram'
WHERE NOT EXISTS (
  SELECT 1
  FROM "project_attachment_types"
  WHERE "doc_type_name" = 'system_diagram'
);
